### ISSUE TITLE
Generate an ASCT+B compliant graph from a set of input triples.

### ISSUE THREAD

**Issue by dosumis** [obophenotype/CCF_graphs#2]
You should be able to use the SELECT queries from CCF_tools with multiple specified objectProperties + subClassOf

OPS: part_of + connected_to  (overlaps is a superPropertyOf of part_of, so we would need conditionality in the query to test for this without just doubling up on the part_of edges)

As with CCF.owl generation, this requires the **_redundant_** graph.  At the time of writing, the redundant graph _does 
 not_ have any subClassOf between named classes, but this is in the **_closure_** graph.

**Comment by anitacaron** [comment]
I did some testing here with the Kidney table.  https://github.com/obophenotype/CCF_graphs/blob/main/sparql/kidney.rq

**Comment by dosumis** [comment]
>  I did some testing here with the Kidney table. https://github.com/obophenotype/CCF_graphs/blob/main/sparql/kidney.rq

I think this tests all(s) by all(o) when we should be testing pairs as we do on CCF_tools: 

```sparql
VALUES (?subject ?object) {
              (UBERON:1234567 UBERON:7654321),
              ...
}
```

**Comment by dosumis** [comment]
Note - spec in first comment edited to update

**Comment by anitacaron** [comment]
Is it still an issue here?
