### ISSUE TITLE
Add ontobio / ogr.py  to container

### ISSUE THREAD

**Issue by dosumis** [obophenotype/CCF_graphs#8]
[ontobio](https://github.com/biolink/ontobio) and the command line tool that comes with it - ogr.py, are useful for generating subgraphs for visualization.  Please add these to the docker container.  (managing mixed js/python dependencies on this locally are a pain).

**Comment by anitacaron** [comment]
Updated Dockerfile

https://github.com/obophenotype/CCF_tools/blob/master/Dockerfile

**Comment by anitacaron** [comment]
Also updated the run.sh here to use the ccf-tools-dep container

https://github.com/obophenotype/CCF_graphs/blob/main/run.sh

**Comment by dosumis** [comment]
Not finding ogr.py:

```
> CCF_graphs % ./run.sh ogr.py -h
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "ogr.py": executable file not found in $PATH: unknown.
```

**Comment by anitacaron** [comment]
Can you try without `.py` ?

**Comment by dosumis** [comment]
Same

**Comment by anitacaron** [comment]
Ok, now the image was updated with ontobio. Should work now, after doing a `docker pull anitacaron/ccf-tools-dep`

**Comment by dosumis** [comment]
Looks like it's working now.  Thanks!
